In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
a=50
b=50
c=a+b
print(c)

100


In [ ]:
l1=[1,2,3,4,5,6,7]
l2=[8,9,10,11]
l3=l2+l1
print(l3)
print(l1)
for x in l1:
  print(x)

[8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]
1
2
3
4
5
6
7


In [ ]:
l1=[1,1,2,2,3,3,4,4,4,5,5,5,6,6]
l2=set(l1)
print(l2)


{1, 2, 3, 4, 5, 6}


In [ ]:
 l2=[1,2,3,4,5,6,7,8,9]


In [ ]:
a=input("Enter name: ")
b=a[::-1]
if a==b:
  print("The String is Palindrome")
else:
  print("The string is not a Palindrome")

Enter name: joint
The string is not a Palindrome


In [ ]:
a=["a","b","c","d",]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']


In [ ]:
list=["red","orange","pink","black"]
print(list)
list.clear()
print(list)

['red', 'orange', 'pink', 'black']
[]


In [ ]:
nums=[1,2,3,4,1,7,8,1]
print(nums)
nums.count(1)

[1, 2, 3, 4, 1, 7, 8, 1]


3

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
A=[1,2,3,4]
B=[5,6,7,8]
A.extend(B)
print(A)
print(B)

[1, 2, 3, 4, 5, 6, 7, 8]
[5, 6, 7, 8]


In [ ]:
a=(5,)
print(a)
print(type(a))

(5,)
<class 'tuple'>


In [ ]:
a=6
type(a)

int

In [ ]:
b=(6.5,7.4,4.5,2.1)
print(b)

(6.5, 7.4, 4.5, 2.1)


In [ ]:
c=("hello",2.34,23)
c

('hello', 2.34, 23)

In [ ]:
a=(1,2,3,4,"hello")

In [ ]:
a={
    "name","joy"
    "age",23,
    "education","btech"
    }
print(a)
len(a)

{'joyage', 'name', 23, 'education', 'btech'}


5

In [ ]:
a={1,2,3,4,5}
print(a)


{1, 2, 3, 4, 5}


In [ ]:
a={1,2,3,3,4,4,5,5,6,7,7,1}
print(a)

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
def add():
  a=2
  b=3
  sum=a+b
  print(sum)
add()


5


In [ ]:
import numpy as np
A1=np.array([1,2,3,4])
print(A1)
A1.size

[1 2 3 4]


4

In [ ]:
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [ ]:
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array=([[[0.,0.,0.,0.,],
       [0.,0.,0.,0.,],
       [0.,0.,0.,0.,]],

       [[0.,0.,0.,0.,],
        [0.,0.,0.,0.,],
        [0.,0.,0.,0.,]]])
print(array)

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]], [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]


In [ ]:
a1=np.ones